#!/usr/bin/env bash

# TODO: https://github.com/elkowar/eww/issues/833
bspc subscribe node_state | while read -r _ _ _ _ state flag; do
  if [ "$state" != "fullscreen" ]; then
    continue
  fi

  if [ "$flag" == on ]; then
    eww close bar
  else
    eww open bar
    eww reload
  fi
done &
